#!/bin/bash

# Define a function to generate an automation script
generate_script() {
    local script_name=$1
    local action=$2
    local trigger=$3

    cat <<EOF > $script_name
#!/bin/bash

# Automation script generated by dxse_generate_a_auto.sh

# Define the action to be taken
-action_fn() {
    $action
}

# Define the trigger for the action
-trigger_fn() {
    $trigger
}

# Main script
main() {
    -trigger_fn && -action_fn
}

main
EOF
    chmod +x $script_name
}

# Prompt user for input
echo "Enter script name: "
read script_name
echo "Enter action (e.g. 'echo Hello World'): "
read action
echo "Enter trigger (e.g. 'sleep 5"): "
read trigger

# Generate the script
generate_script $script_name $action $trigger

echo "Script generated: $script_name"